### ISSUE TITLE
Couldn't retrieve the server process ID

### ISSUE THREAD

**Issue by TheoDurr** [MinecraftServerControl/mscs#220]
Hello guys,
I know that much issues were opened with this error message, however I can't find someone with the same issue than mine.

I created a server with `forge-1.12.2-14.23.5.2821` to use the `FTBPresentsDirewolf20112-2.5.0-1.12.2` modpack.

After downloading the jar installer and using the command `java -jar forge-1.12.2-14.23.5.2821-universal.jar --installServer`, everithing is going fine until I try to launch the server.

Here is my `mscs.properties` :
```
mscs-enabled=true
mscs-server-version=1.12.2
mscs-server-jar=forge-1.12.2-14.23.5.2821-universal.jar
mscs-initial-memory=1024M
mscs-maximum-memory=8192M
mscs-server-args=nogui
```
I got this error after lauching my server with `mscs start ftb` : `Error starting the server: couldn't retrieve the server's process ID.`

And here is my `console.out` file 
```
A problem occurred running the Server launcher.java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.run(ServerLaunchWrapper.java:70)
        at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:34)
Caused by: java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
        ... 6 more
```

The server tries to run on a Debian 8 VPS with java version `12.0.1`

**Comment by sandain** [comment]
Hi @TheoDurr. I wonder if this is an issue with Java 12?  Can you try running with an older version of Java, say Java 8?

**Comment by TheoDurr** [comment]
You got right, it was an Issue with java12. 
I didn't remembered it was so hard to install java8 😮 

Thanks anyway !
