### ISSUE TITLE
Minecraft Forge 1.18.1 not starting

### ISSUE THREAD

**Issue by xathon** [MinecraftServerControl/mscs#307]
I followed the manual to edit the run.sh file and added the full path to all the libraries there and in the unix_args file. Unfortunately, once I pass the launch script with `mscs-server-command=/opt/mscs/server/newForge/run.sh` , the server doesn't start up anymore. The logfile says nothing more than:
```
[01:29:00] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.55, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --nogui, mscs-world=MineCraft]
[01:29:00] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Private Build
[01:29:00] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/opt/mscs/server/newForge/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[01:29:00] [main/INFO]: Found mod file FallingTree-1.18.1-3.1.0.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:29:00] [main/INFO]: Found mod file FastFurnace-1.18.1-6.0.1.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:29:00] [main/INFO]: Found mod file FastWorkbench-1.18.1-6.0.0.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:29:00] [main/INFO]: Found mod file MoreMobGriefingOptions-1.18.1-2.0.1.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:29:00] [main/INFO]: Found mod file Placebo-1.18.1-6.0.3.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
```
My configuration files are like this:
mscs.properties:
```
mscs-enabled=true
mscs-initial-memory=1G
mscs-maximum-memory=4G
mscs-client-version=1.18.1
mscs-server-version=1.18.1
mscs-server-command=/opt/mscs/server/newForge/run.sh
mscs-server-url=
```
run.sh:
```sh
java @/opt/mscs/server/newForge/user_jvm_args.txt @/opt/mscs/server/newForge/libraries/net/minecraftforge/forge/1.18.1-
39.0.55/unix_args.txt --nogui "$@"
```
unix_args.txt:
```
-p /opt/mscs/server/newForge/libraries/cpw/mods/bootstraplauncher/1.0.0/bootstraplauncher-1.0.0.jar:/opt/mscs/server/newForge/libraries/cpw/mods/securejarhandler/1.0.1/securejarhandler-1.0.1.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar
--add-modules ALL-MODULE-PATH
--add-opens java.base/java.util.jar=cpw.mods.securejarhandler
--add-exports java.base/sun.security.util=cpw.mods.securejarhandler
-DignoreList=bootstraplauncher-1.0.0.jar,securejarhandler-1.0.1.jar,asm-commons-9.2.jar,asm-util-9.2.jar,asm-analysis-9.2.jar,asm-tree-9.2.jar,asm-9.2.jar
-DlibraryDirectory=libraries
-DlegacyClassPath=/opt/mscs/server/newForge/libraries/cpw/mods/securejarhandler/1.0.1/securejarhandler-1.0.1.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm/9.2/asm-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-commons/9.2/asm-commons-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-tree/9.2/asm-tree-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-util/9.2/asm-util-9.2.jar:/opt/mscs/server/newForge/libraries/org/ow2/asm/asm-analysis/9.2/asm-analysis-9.2.jar:/opt/mscs/server/newForge/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar:/opt/mscs/server/newForge/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar:/opt/mscs/server/newForge/libraries/net/minecraftforge/eventbus/5.0.3/eventbus-5.0.3.jar:/opt/mscs/server/newForge/libraries/net/minecraftforge/forgespi/4.0.10/forgespi-4.0.10.jar:/opt/mscs/server/newForge/libraries/net/minecraftforge/coremods/5.0.1/coremods-5.0.1.jar:/opt/mscs/server/newForge/libraries/cpw/mods/modlauncher/9.1.0/modlauncher-9.1.0.jar:/opt/mscs/server/newForge/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:/opt/mscs/server/newForge/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar:/opt/mscs/server/newForge/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar:/opt/mscs/server/newForge/libraries/org/apache/maven/maven-artifact/3.6.3/maven-artifact-3.6.3.jar:/opt/mscs/server/newForge/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar:/opt/mscs/server/newForge/libraries/net/jodah/typetools/0.8.3/typetools-0.8.3.jar:/opt/mscs/server/newForge/libraries/org/apache/logging/log4j/log4j-api/2.15.0/log4j-api-2.15.0.jar:/opt/mscs/server/newForge/libraries/org/apache/logging/log4j/log4j-core/2.15.0/log4j-core-2.15.0.jar:/opt/mscs/server/newForge/libraries/org/apache/logging/log4j/log4j-slf4j18-impl/2.15.0/log4j-slf4j18-impl-2.15.0.jar:/opt/mscs/server/newForge/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:/opt/mscs/server/newForge/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar:/opt/mscs/server/newForge/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar:/opt/mscs/server/newForge/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/opt/mscs/server/newForge/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar:/opt/mscs/server/newForge/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar:/opt/mscs/server/newForge/libraries/com/google/guava/guava/31.0.1-jre/guava-31.0.1-jre.jar:/opt/mscs/server/newForge/libraries/com/google/code/gson/gson/2.8.8/gson-2.8.8.jar:/opt/mscs/server/newForge/libraries/net/minecraftforge/fmlloader/1.18.1-39.0.55/fmlloader-1.18.1-39.0.55.jar:/opt/mscs/server/newForge/libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-extra.jar:/opt/mscs/server/newForge/libraries/com/github/oshi/oshi-core/5.8.2/oshi-core-5.8.2.jar:/opt/mscs/server/newForge/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar:/opt/mscs/server/newForge/libraries/com/mojang/authlib/3.2.38/authlib-3.2.38.jar:/opt/mscs/server/newForge/libraries/com/mojang/brigadier/1.0.18/brigadier-1.0.18.jar:/opt/mscs/server/newForge/libraries/com/mojang/datafixerupper/4.0.26/datafixerupper-4.0.26.jar:/opt/mscs/server/newForge/libraries/com/mojang/javabridge/1.2.24/javabridge-1.2.24.jar:/opt/mscs/server/newForge/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar:/opt/mscs/server/newForge/libraries/io/netty/netty-all/4.1.68.Final/netty-all-4.1.68.Final.jar:/opt/mscs/server/newForge/libraries/it/unimi/dsi/fastutil/8.5.6/fastutil-8.5.6.jar:/opt/mscs/server/newForge/libraries/net/java/dev/jna/jna/5.9.0/jna-5.9.0.jar:/opt/mscs/server/newForge/libraries/net/java/dev/jna/jna-platform/5.9.0/jna-platform-5.9.0.jar:/opt/mscs/server/newForge/libraries/org/slf4j/slf4j-api/1.8.0-beta4/slf4j-api-1.8.0-beta4.jar
cpw.mods.bootstraplauncher.BootstrapLauncher
--launchTarget forgeserver
--fml.forgeVersion 39.0.55
--fml.mcVersion 1.18.1
--fml.forgeGroup net.minecraftforge
--fml.mcpVersion 20211210.034407
```
Am I doing something wrong?

**Comment by sandain** [comment]
Please post the contents of the `console.out` file. It may have more information than the log file.

**Comment by xathon** [comment]
Yeah, I just found that out looking at #293 .
console.out:
```
[01:44:12] [main/INFO]: ModLauncher running: args [--launchTarget, forgeserver, --fml.forgeVersion, 39.0.55, --fml.mcVersion, 1.18.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20211210.034407, --nogui, mscs-world=MineCraft]
[01:44:12] [main/INFO]: ModLauncher 9.1.0+9.1.0+main.6690ee51 starting: java version 17.0.1 by Private Build
[01:44:12] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/opt/mscs/server/newForge/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%2319!/ Service=ModLauncher Env=SERVER
[01:44:12] [main/INFO]: Found mod file FallingTree-1.18.1-3.1.0.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:44:12] [main/INFO]: Found mod file FastFurnace-1.18.1-6.0.1.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:44:12] [main/INFO]: Found mod file FastWorkbench-1.18.1-6.0.0.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:44:12] [main/INFO]: Found mod file MoreMobGriefingOptions-1.18.1-2.0.1.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
[01:44:12] [main/INFO]: Found mod file Placebo-1.18.1-6.0.3.jar of type MOD with locator {mods folder locator at /opt/mscs/worlds/MineCraft/mods}
Exception in thread "main" java.io.UncheckedIOException: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-extra.jar]
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.impl.Jar.<init>(Jar.java:74)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:58)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:50)
        at cpw.mods.securejarhandler@1.0.1/cpw.mods.jarhandling.SecureJar.from(SecureJar.java:42)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.55/net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.getMinecraftPaths(CommonServerLaunchHandler.java:56)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.55/net.minecraftforge.fml.loading.moddiscovery.MinecraftLocator.scanMods(MinecraftLocator.java:27)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.55/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:64)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.55/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:180)
        at MC-BOOTSTRAP/fmlloader@1.18.1-39.0.55/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:100)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
        at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
        at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
        at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.run(Launcher.java:87)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
        at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.0/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
        at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.io.IOException: Invalid paths argument, contained no existing paths: [libraries/net/minecraft/server/1.18.1-20211210.034407/server-1.18.1-20211210.034407-extra.jar]
        ... 27 more
```
I double checked my unix_args.txt, it includes the path that the exception mentions and has the absolute path in it. I also checked if the .jar exists in that folder, which it does.

**Comment by sandain** [comment]
Hi Xanthon.  Everything looks correct to me. Maybe the file is corrupt?  Try reinstalling the Forge package.

**Comment by xathon** [comment]
Seems like it was indeed a faulty forge installation. It's working great now, thanks!
